### ISSUE TITLE
Social handle links in the footer .

### ISSUE THREAD

**Issue by heyvats21** [JayrajSingh65/NikeStore#4]
I will add your social handle links of facebook, twitter, insta .
![image](https://user-images.githubusercontent.com/81029204/194743119-ed8b1da3-ed9d-4ec5-9dc4-b39b8dbce647.png)

My suggestion- Please host your website and you have made an awesome UI🤩
![image](https://user-images.githubusercontent.com/81029204/194743130-9d60b992-a43f-4864-80de-46f2b9b7eda3.png)

assign me under hactoberfest

**Comment by JayrajSingh65** [comment]
Thanks for showing interest in this project you can link my insta and twitter id.

- twitter id => go check out in my profile 
- instagram id => jayrajsingh90

**Comment by heyvats21** [comment]
Hey @JayrajSingh65 check it out i have made changes in it

**Comment by JayrajSingh65** [comment]
make them working by javascript

**Comment by heyvats21** [comment]
@JayrajSingh65  i am not able to understand what uh r trying to say...  my task was to add the social media links of your social media handles .😅

**Comment by JayrajSingh65** [comment]
> @JayrajSingh65 i am not able to understand what uh r trying to say... my task was to add the social media links of your social media handles .😅

when user click on icons it should redirected to my social media make them button
